name: Ohm
website: ohm.sh
description: My little corner of the web
markdown: redcarpet
lsi: false
timezone: Europe/Copenhagen
encoding: utf-8

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from

navigation:
- text: Blog
  url: /
  symbol: fa-pencil
- text: CV
  url: /cv.html
  symbol: fa-star
- text: Wish-list
  url: /wishlist.html
  symbol: fa-gift
- text: Master Thesis
  title: Exception Handling in Communicating Sequential Processes
  url: /files/thesis.pdf
  symbol: fa-flask
- text: Bachelor Thesis
  title: Korte Kurver p√• Krumme Flader
  url: /files/bachelors.pdf
  symbol: fa-flask
